Update .gitpod.yml

diff --git a/.gitpod.yml b/.gitpod.yml
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -4,14 +4,14 @@ image:
 # [ NOTE ] =>
 # - https://community.gitpod.io/t/knative-development-on-gitpod/2814/2
 tasks:
-  - init: >
-      sudo usermod -aG docker gitpod || true
-      bash /workspace/container-images/scripts/docker-buildx-installer || true
-      while [ -z "$SSH_PUB_KEY" ] ; do
-      printf "\n❗ The SSH_PUB_KEY environment variable is required. Please enter its value.\n" &&
-      read -s -p "SSH_PUB_KEY: " SSH_PUB_KEY ;
-      done ; gp env SSH_PUB_KEY=$SSH_PUB_KEY && printf "\nThanks\n";
-      mkdir -p ~/.ssh && open ~/.ssh/authorized_keys
+  - init: |
+      sudo usermod -aG docker gitpod || true && \
+      bash /workspace/container-images/scripts/docker-buildx-installer || true && \
+      while [ -z "$SSH_PUB_KEY" ] ; do \
+      printf "\n❗ The SSH_PUB_KEY environment variable is required. Please enter its value.\n" && \
+      read -s -p "SSH_PUB_KEY: " SSH_PUB_KEY ; \
+      done ; gp env SSH_PUB_KEY=$SSH_PUB_KEY && printf "\nThanks\n"; && \
+      mkdir -p ~/.ssh && open ~/.ssh/authorized_keys && \
       echo "${SSH_PUB_KEY}" | tee ~/.ssh/authorized_keys > /dev/null
   - name: "start Docker daemon"
     command: sudo docker-up
